config/routes.rb
require 'subscribem/constraints/subdomain_required'

Subscribem::Engine.routes.draw do

  namespace :account do
    get 'users/new'
  end

  get 'users/new'

  constraints(Subscribem::Constraints::SubdomainRequired) do
    scope module: 'account' do
      root to: "dashboard#index", as: :account_root
      get "/sign_in", to: "sessions#new"
      post "/sign_in", to: "sessions#create", as: :sessions
      get "/sign_up", to: "users#new", as: :user_sign_up
      post "/sign_up", to: "users#create", as: :do_user_sign_up
    end
  end


  get "/signup", to: "accounts#new", as: :sign_up
  post "/accounts", to: "accounts#create", as: :accounts

  root "dashboard#index"
end

app/models/subscribem/account.rb
module Subscribem
  class Account < ActiveRecord::Base
    EXCLUDED_SUBDOMAINS = %w(admin)

    has_many :members, class_name: "Subscribem::Member"
    has_many :users, through: :members

    belongs_to :owner, class_name: "::Subscribem::User"
    accepts_nested_attributes_for :owner

    validates :subdomain, presence: true, uniqueness: true
    validates_format_of :subdomain, with: /\A[\w-]+\Z/i,
      message: "is not allowed. Please choose another subdomain."
    validates_exclusion_of :subdomain, in: EXCLUDED_SUBDOMAINS,
      message: "is not allowed. Please choose another subdomain."

    before_validation do
      self.subdomain = subdomain.to_s.downcase
    end

    def self.create_with_owner(params={})
      account = new(params)
      if account.save
        account.users << account.owner
      end
      account
    end

  end
end

app/models/subscribem/member.rb
module Subscribem
  class Member < ActiveRecord::Base
    belongs_to :account, class_name: "Subscribem::Account"
    belongs_to :user, class_name: "Subscribem::User"
  end
end

app/models/subscribem/user.rb
module Subscribem
  class User < ActiveRecord::Base
    has_secure_password
  end
end

app/controllers/subscribem/account/dashboard_controller.rb
require_dependency "subscribem/application_controller"

module Subscribem
  class Account::DashboardController < ApplicationController
    before_filter :authenticate_user!

    def index
    end
  end
end

app/controllers/subscribem/account/sessions_controller.rb
require_dependency "subscribem/application_controller"

module Subscribem
  class Account::SessionsController < ApplicationController
    def new
      @user = User.new
    end

    def create
      if env["warden"].authenticate(scope: :user)
        logger.info("Session created")
        redirect_to root_path, notice: "You are now signed in."
      else
        logger.error("Failed to create session")
        @user = User.new
        flash[:error] = "Invalid email or password."
        render action: "new"
      end
    end
  end
end

app/controllers/subscribem/account/users_controller.rb
require_dependency "subscribem/application_controller"

module Subscribem
  class Account::UsersController < ApplicationController
    def new
      @user = Subscribem::User.new
    end

    def create
      account = Subscribem::Account.find_by!(subdomain: request.subdomain)
      user = account.users.create(user_params)

      force_authentication!(account, user)

      flash[:success] = "You have signed up successfully."
      redirect_to root_path
    end

    private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
  end
end

app/controllers/subscribem/accounts_controller.rb
require_dependency "subscribem/application_controller"

module Subscribem
  class AccountsController < ApplicationController
    def new
      @account = Subscribem::Account.new
      @account.build_owner
    end

    def create
      @account = Subscribem::Account.create_with_owner(account_params)

      if @account.valid?
        force_authentication!(@account, @account.owner)

        flash[:success] = "Your account has been successfully created."
        redirect_to subscribem.root_url(subdomain: @account.subdomain)
      else
        flash[:error] = "Sorry, your account could not be created."
        render :new
      end
    end

    private

    def account_params 
      params.require(:account).permit(:name, :subdomain,
                                      { owner_attributes: 
                                        [:email, :password, :password_confirmation]})
    end
  end
end

app/controllers/subscribem/application_controller.rb
module Subscribem
  class ApplicationController < ::ApplicationController
  end
end

app/controllers/subscribem/dashboard_controller.rb
require_dependency "subscribem/application_controller"

module Subscribem
  class DashboardController < ApplicationController
    def index

    end
  end
end

app/helpers/subscribem/account/dashboard_helper.rb
module Subscribem
  module Account::DashboardHelper
  end
end

app/helpers/subscribem/account/sessions_helper.rb
module Subscribem
  module Account::SessionsHelper
  end
end

app/helpers/subscribem/account/users_helper.rb
module Subscribem
  module Account::UsersHelper
  end
end

app/helpers/subscribem/accounts_helper.rb
module Subscribem
  module AccountsHelper
  end
end

app/helpers/subscribem/application_helper.rb
module Subscribem
  module ApplicationHelper
  end
end

app/helpers/subscribem/dashboard_helper.rb
module Subscribem
  module DashboardHelper
  end
end

app/views/layouts/subscribem/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Subscribem</title>
  <%= stylesheet_link_tag    "subscribem/application", media: "all" %>
  <%= javascript_include_tag "subscribem/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
  Signed in as <%= current_user.email %>
<% end %>

<%= yield %>

</body>
</html>

app/views/subscribem/account/dashboard/index.html.erb
<% flash.each do |k, v| %>
  <div class="flash"><%= k %> -- <%= v %></div>
<% end %>

Your account's dashboard. Coming soon.

app/views/subscribem/account/users/_form.html.erb
<p>
  <%= user.label :email %><br>
  <%= user.email_field :email %><br>
</p>
<p>
  <%= user.label :password %><br>
  <%= user.password_field :password %>
</p>
<p>
  <%= user.label :password_confirmation %><br>
  <%= user.password_field :password_confirmation %><br>
</p>

app/views/subscribem/account/users/new.html.erb
<h2>Sign Up</h2>
<%= form_for(@user, url: do_user_sign_up_url) do |user| %>
  <%= render "subscribem/account/users/form", user: user %>
  <%= user.submit "Sign up" %>
<% end %>

app/views/subscribem/accounts/new.html.erb
<% flash.each do |k, v| %>
  <div class="flash"><%= k %> -- <%= v %></div>
<% end %>
<h2>Sign up</h2>
<%= form_for(@account) do |account|  %>
  <%= account.error_messages %>
  <p>
    <%= account.label :name %><br>
    <%= account.text_field :name %>
  </p>
  <p>
    <%= account.label :subdomain %><br>
    <%= account.text_field :subdomain %>
  </p>
  <%= account.fields_for :owner do |owner| %>
    <%= render "subscribem/account/users/form", user: owner %>
  <% end %>
  <%= account.submit %>
<% end %>

app/views/subscribem/dashboard/index.html.erb
<% flash.each do |k, v| %>
  <div class="flash"><%= k %> -- <%= v %></div>
<% end %>

<%= link_to "Account Sign Up", sign_up_path %>